[theme]
primaryColor = "#1e3a5f"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
headless = true
enableCORS = false
address = "localhost"
port = 8501
enableXsrfProtection = true
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
